version: 2.1
jobs:
  build:
    docker:
      # Use tags "latest or bionic" for Ubuntu 18.04.4 LTS
      # Use tags "edge or focal" for Ubuntu 20.04 LTS"
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0' # REQUIRED:: Put as 'android-X.Y' format as-in "manifest_pb" repository
      PBRP_BRANCH: 'android-9.0' # OPTIONAL:: If not default 'android-9.0', define other bootable_recovery branch
      VERSION: '3.0.0' # as of now, the current PBRP version
      MAINTAINER: '@kanged99' # REQUIRED:: Replace your Telegram ID, if unavailable then use GitHub Username
      VENDOR: 'realme' # REQUIRED:: Input Product Vendor or Manufacturer
      CODENAME: 'RMX1851' # REQUIRED:: Input Device Codename
      FLAVOR: 'eng' # REQUIRED:: Input 'eng' or 'userdebug'
      #BUILD_LUNCH: 'omni_RMX1851-eng' # DEPRICATED:: set like 'omni_$CODENAME-userdebug' or 'omni_$CODENAME-eng'
      #TEST_BUILD: 'true' # OPTIONAL:: Use for Testing Purpose, Comment-out/delete for Official build
      PB_OFFICIAL: 'true' # REQUIRED-FOR-TEAM:: Uncomment only for Stable Official builds
      # EXTRA_CMD: "" # OPTIONAL:: USE DOUBLE-QUOTE: If you need to modify or patch a few things with commands after `repo sync`, write in single line separated by semicolon ';' if needed
      # PB_ENGLISH: 'true' # OPTIONAL:: If you want only English Language
      CHANGELOG: | # Write anything under the pipe '|' character keeping the 2-character-space, no quote required
          - add magisk 21.0 zip\n
          - minor fixes and improvements
    working_directory: /home/builder/pitchblack
    steps: 
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: android-9.0 # REPLACE CURRENT BRANCH NAME WITHIN QUOTE
          context: org-global ## ONLY FOR TEAM DEVELPERS
          ## If you are not in Team, then you have to add $GitHubMail, $GitHubName and $GITHUB_TOKEN in the environment variables
