version: 2.1
# It's time we use Real CI Config v2.1
executors:
  worker:
    docker:
      - image: fr3akyphantom/droid-builder:latest
        # Use tags "latest or bionic" for Ubuntu 18.04.4 LTS
        # Use tags "edge or focal" for Ubuntu 20.04 LTS"
        auth:
          # This is Required from now on
          username: "$DOCKERHUB_USERNAME"
          password: "$DOCKERHUB_PASSWORD"
# Read carefully, and remove unnecessary key-value pair & these comments before pushing
jobs:
  build:
    executor: worker
    environment:
      # --- {{ These below 4 variables are Prime Requirement because build will not start if any of them are unset or absent }} ---
      MANIFEST_BRANCH: 'android-9.0' # Put as 'android-X.Y' format as-in "manifest_pb" repository
      VENDOR: 'android-9.0' # Input Product Vendor or Manufacturer
      CODENAME: 'RMX1851' # Rnput Device Codename
      FLAVOR: 'eng' # Input "eng" or "userdebug", `BUILD_LUNCH` variable key is DEPRICATED
      # --- {{ This variable to change bootable branch is OPTIONAL }} ---
      PBRP_BRANCH: 'android-9.0' # If not default "android-9.0", define other bootable_recovery branch
      # ---------------------------------\
      VERSION: "3.0.0" # {{ DEPRICATED }} The current PBRP version, you might wanna avoid using it because it is dynamically fetched by build system
      # ---------------------------------/
      # --- {{ REQUIRED:: any one key: Use only one of the 3 variables specifying your build type }} ---
      TEST_BUILD: true   # For Dev/Test Builds Only
      #BETA_BUILD: true   # For Beta Release Builds Only
      #PB_OFFICIAL: true  # For Official Organisation Builds
      # --- {{ OPTIONAL: Wanna extend the build script? Wanna add some commands just before lunch? }} ---
      EXTRA_CMD: "" # Whatever commands you wanna run inside working directory
      # --- {{ OPTIONAL: Wanna truncate all other languages except English? }} ---
      PB_ENGLISH: true # If you want only English Language
      # --- {{ REQUIRED: Only for Device Maintainers who want to get notified about the build in Telegram Maintainers' Group }} ---
      MAINTAINER: '@kanged99' # Replace your Telegram ID, if unavailable then use GitHub User URI
      # --- {{ OPTIONAL: Wanna add some fancy/informative Changelog while publishing your Build? }} ---
      CHANGELOG: |
        What's been done?
        - bump to 3.5 twrp
        - Update lock pattern types for A11
        - Improve logd
        - Misc        
        What's fixed?
        - nothing
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'test'
          context: org-global ## ONLY FOR TEAM DEVELPERS
          ## If you are not in Team, then you have to add $GitHubMail, $GitHubName and $GITHUB_TOKEN in the environment variables
