version: 2.1
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      PBRP_BRANCH: 'ozip'
      VERSION: '2.9.1'
      VENDOR: 'realme'
      CODENAME: 'RMX1851'
      BUILD_LUNCH: 'omni_RMX1851-eng'
      MAINTAINER: '@kanged99'
      #PB_OFFICIAL: 'true'
      TEST_BUILD: 'true'
    working_directory: /home/builder/pitchblack
    steps: 
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: test
          context: org-global
